apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    run: nginx
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jovianx-metering-service-access
  namespace: keda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jovianx-metering
  template:
    metadata:
      labels:
        app: jovianx-metering
    spec:
      volumes:
        - name: data
          emptyDir: {}
      containers:
        - name: nginx
          image: 'nginx:latest'
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /usr/share/nginx/html/metrics
          #  cat <<EOF >/usr/share/nginx/html/metrics/worker.json
          # {
          # "worker": {
          #   "scale_num": 5
          #  }
          
          # }
          # EOF
          # cat <<EOF >/usr/share/nginx/html/metrics/worker1.json
          # {
          # "worker": {
          #   "scale_num": 2
          #  }
          
          # }
          # EOF
          # cat <<EOF >/usr/share/nginx/html/metrics/worker2.json
          # {
          # "worker": {
          #   "scale_num": 4
          #  }
          
          # }
          # EOF
