apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: mapi2-scaledobject
  namespace: keda
spec:
  idleReplicaCount: 1
  minReplicaCount: 1
  maxReplicaCount: 5
  scaleTargetRef:
    kind: StatefulSet
    name: dummy2
  triggers:
    - type: metrics-api
      metadata:
        targetValue: "4"
        url: "http://10.233.102.54/metrics/worker2.json"
        valueLocation: 'worker.scale_num'
